# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x2668c8e5840
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.19901939 0.79040752 0.71681037]
 [0.02035661 0.08212227 0.07049977]
 [0.79587973 0.23925519 0.08890003]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.19901939 0.79040752 0.71681037]
 [0.02035661 0.08212227 0.07049977]
 [0.79587973 0.23925519 0.08890003]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

200

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)
np.info(arr1_1)
print(arr1_1)

class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2668b608410
byteorder:  little
byteswap:  False
type: float64
[[0.76404057 0.65689724 0.59641576 0.81877156]
 [0.79391479 0.23273407 0.06400266 0.99050948]
 [0.00122886 0.21584424 0.6301809  0.08764052]]


In [13]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['three', 'fifteen', 'find', 'missing', 'teen'])
print(arr1_2)

['three' 'fifteen' 'find' 'missing' 'teen']


In [14]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3,4), dtype='f')
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.array(["False"] * 9)
arr2_1 = arr2_1.reshape((3,1,3))
print(arr2_1)

[[['False' 'False' 'False']]

 [['False' 'False' 'False']]

 [['False' 'False' 'False']]]


In [20]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
...
print(arr2_2)

[['False' 'False' 'False']
 ['False' 'False' 'False']
 ['False' 'False' 'False']]


In [21]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
parni = []

for i in range(10, 21):
    if i % 2 == 0:
        parni.append(i)
        
arr2_3 = np.array(parni)
arr2_3 = arr2_3.reshape((2,3))
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [22]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [23]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[40 21 13 15]
 [25 24 23 34]
 [22 27 24 42]
 [49 19 31 32]]


In [24]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

34


In [25]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[49 19 31 32]


In [26]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[40 21 13 15]
 [25 24 23 34]]


In [27]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[21 13]
 [24 23]
 [27 24]
 [19 31]]


In [28]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[40 21 13 15]
 [22 27 24 42]]


In [29]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[40 21 25 24 23 34 22 27 24 42 49 31 32]


### ЗАВДАННЯ 3

In [30]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.linspace(10, 100, 20)
arr3_1 = arr3_1.reshape(4,5)
print(arr3_1)

[[ 10.          14.73684211  19.47368421  24.21052632  28.94736842]
 [ 33.68421053  38.42105263  43.15789474  47.89473684  52.63157895]
 [ 57.36842105  62.10526316  66.84210526  71.57894737  76.31578947]
 [ 81.05263158  85.78947368  90.52631579  95.26315789 100.        ]]


In [31]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

43.1578947368421


In [32]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[33.68421053 38.42105263 43.15789474 47.89473684 52.63157895]


In [33]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[19.47368421 43.15789474 66.84210526 90.52631579]


In [34]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[38.42105263 43.15789474]
 [62.10526316 66.84210526]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [35]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [37]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.17835615 0.47527392 0.39706854 0.08070744 0.69947436]
 [0.73156921 0.18383006 0.48640169 0.45260717 0.34454975]
 [0.8765643  0.41386779 0.56164633 0.16266121 0.55085574]
 [0.1332757  0.1746993  0.90413599 0.91033447 0.76931017]
 [0.09816263 0.85025861 0.97838843 0.22069718 0.20327667]]
...
[0.17835615 0.18383006 0.56164633 0.91033447 0.20327667]


In [38]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.17835615 0.73156921 0.8765643  0.1332757  0.09816263]
 [0.47527392 0.18383006 0.41386779 0.1746993  0.85025861]
 [0.39706854 0.48640169 0.56164633 0.90413599 0.97838843]
 [0.08070744 0.45260717 0.16266121 0.91033447 0.22069718]
 [0.69947436 0.34454975 0.55085574 0.76931017 0.20327667]]


In [39]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.05597697850802654


In [40]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-0.26772064  0.94436017  0.50358879 -0.48740465 -0.19950528]
 [ 3.69857242  5.61059541 -5.16976795 -2.41381298  0.90803053]
 [-3.93332085 -6.02352328  5.43785247  2.27832528  0.38592452]
 [ 2.44538351  5.87602594 -5.2452402  -1.13887627  0.14981283]
 [ 0.93549097 -1.31168431  0.90263135  0.60247879 -0.80247364]]


### ЗАВАДАННЯ 4

In [41]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.linspace(100, 200, 36)
mat4_1 = mat4_1.reshape(6,6)
print(mat4_1)

[[100.         102.85714286 105.71428571 108.57142857 111.42857143
  114.28571429]
 [117.14285714 120.         122.85714286 125.71428571 128.57142857
  131.42857143]
 [134.28571429 137.14285714 140.         142.85714286 145.71428571
  148.57142857]
 [151.42857143 154.28571429 157.14285714 160.         162.85714286
  165.71428571]
 [168.57142857 171.42857143 174.28571429 177.14285714 180.
  182.85714286]
 [185.71428571 188.57142857 191.42857143 194.28571429 197.14285714
  200.        ]]


In [42]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [43]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[100.         117.14285714 134.28571429 151.42857143 168.57142857
  185.71428571]
 [102.85714286 120.         137.14285714 154.28571429 171.42857143
  188.57142857]
 [105.71428571 122.85714286 140.         157.14285714 174.28571429
  191.42857143]
 [108.57142857 125.71428571 142.85714286 160.         177.14285714
  194.28571429]
 [111.42857143 128.57142857 145.71428571 162.85714286 180.
  197.14285714]
 [114.28571429 131.42857143 148.57142857 165.71428571 182.85714286
  200.        ]]


In [44]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
inv4_4

array([[ 6.78146846e+12, -1.38133889e+13, -6.95761050e+12,
         2.81214892e+13, -1.40239337e+13, -1.08024609e+11],
       [ 2.04148622e+13, -1.79141957e+13, -9.24745699e+12,
        -9.61006189e+12,  1.65449666e+13, -1.88114192e+11],
       [ 2.72667875e+13, -8.20161364e+12, -4.57969299e+12,
        -4.02787301e+13, -9.23094368e+12,  3.50241929e+13],
       [-1.63459811e+14,  1.66630368e+14,  5.07289069e+13,
        -1.66454226e+13,  3.18817089e+13, -6.91357499e+13],
       [ 1.29552469e+14, -1.67932168e+14, -1.59408544e+13,
         5.19598370e+13, -3.21307847e+13,  3.44915009e+13],
       [-2.05557758e+13,  4.12309980e+13, -1.40032920e+13,
        -1.35471117e+13,  6.95898661e+12, -8.38050790e+10]])

## 5. Операції над масивами

### ПРИКЛАДИ

In [45]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [46]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [47]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [48]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [49]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [50]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [51]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [52]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [53]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\alexa\AppData\Local\Temp\ipykernel_8216\3347190385.py:2: RuntimeWarning: divide by zero encountered in divide
  K = N / M


In [54]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [55]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [56]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [57]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [58]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [59]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[6 3 1 5 9]
[6 3 1 5 9]
2639519529456 2639519529456
[6 3 1 5 9]
2639519529456 2639519530224


In [60]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [77]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.rand(5,5)
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[0.29627703 0.76124942 0.3664766  0.32901357 0.97330055]
 [0.62982816 0.82940924 0.10656317 0.91885652 0.72797587]
 [0.98100969 0.83848915 0.69294388 0.02235593 0.18896868]
 [0.3451548  0.41612026 0.50648005 0.69602721 0.32970643]
 [0.52911858 0.49494524 0.74261436 0.5400577  0.71958626]]
[2.72631716 3.21263297 2.72376735 2.29348873 3.02632214]


In [78]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)

2.293488731888807


In [79]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[100.29627703 100.76124942 100.3664766  100.32901357 100.97330055]
 [100.62982816 100.82940924 100.10656317 100.91885652 100.72797587]
 [100.98100969 100.83848915 100.69294388 100.02235593 100.18896868]
 [100.3451548  100.41612026 100.50648005 100.69602721 100.32970643]
 [100.52911858 100.49494524 100.74261436 100.5400577  100.71958626]]


In [83]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.multiply(mat5_1, np.diag(mat5_3))
print(mat5_4)

[[29.71548272 76.75632944 36.90160749 33.13035933 98.03042831]
 [63.16942006 83.62884375 10.73015977 92.52520112 73.32142868]
 [98.39162008 84.54436613 69.77455938  2.2511535  19.03284775]
 [34.61774095 41.95715982 50.99896678 70.08717466 33.20789474]
 [53.06862366 49.90503624 74.77602603 54.38166491 72.47642992]]


In [84]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print(np.linalg.matrix_rank(mat5_5))

[[100.29627703 100.76124942 100.3664766  100.32901357 100.97330055
   29.71548272  76.75632944  36.90160749  33.13035933  98.03042831]
 [100.62982816 100.82940924 100.10656317 100.91885652 100.72797587
   63.16942006  83.62884375  10.73015977  92.52520112  73.32142868]
 [100.98100969 100.83848915 100.69294388 100.02235593 100.18896868
   98.39162008  84.54436613  69.77455938   2.2511535   19.03284775]
 [100.3451548  100.41612026 100.50648005 100.69602721 100.32970643
   34.61774095  41.95715982  50.99896678  70.08717466  33.20789474]
 [100.52911858 100.49494524 100.74261436 100.5400577  100.71958626
   53.06862366  49.90503624  74.77602603  54.38166491  72.47642992]]
5
