#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [1]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [2]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [3]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[233 172 205 353 315 294 184 123 243 286]
 [176 174 367 351 152 192 471 279 201 299]
 [252 319 402 204 311 266 324 270 252 405]
 [349 271 342 328 399 298 197 485 373 403]
 [491 224 376 216 142 186 393 369 302 150]
 [180 188 337 209 336 323 353 318 215 261]
 [462 435 149 488 328 285 400 379 341 379]
 [197 290 126 386 290 338 102 190 331 401]
 [166 484 317 355 445 213 225 312 488 324]
 [153 404 258 174 251 145 206 174 215 282]]


0    1    2    3    4    5    6    7    8    9
0  233  172  205  353  315  294  184  123  243  286
1  176  174  367  351  152  192  471  279  201  299
2  252  319  402  204  311  266  324  270  252  405
3  349  271  342  328  399  298  197  485  373  403
4  491  224  376  216  142  186  393  369  302  150
5  180  188  337  209  336  323  353  318  215  261
6  462  435  149  488  328  285  400  379  341  379
7  197  290  126  386  290  338  102  190  331  401
8  166  484  317  355  445  213  225  312  488  324
9  153  404  258  174  251  145  206  174  215  282

In [4]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.07624435 0.25157234 0.73470819]
 [0.75542977 0.67255956 0.61568744]
 [0.06968485 0.51206918 0.17729188]
 [0.42229544 0.926      0.54685349]
 [0.04963574 0.00168132 0.24050087]]


колонка 1  колонка 2  колонка 3
0   0.076244   0.251572   0.734708
1   0.755430   0.672560   0.615687
2   0.069685   0.512069   0.177292
3   0.422295   0.926000   0.546853
4   0.049636   0.001681   0.240501

In [5]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {
    "Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
a = pd.DataFrame(d, index=[10,20,30,40,50])

In [ ]:
a

In [6]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [7]:
str(name_rik[2])

"('Микола', 2003)"

In [45]:
pd.read_csv?

In [46]:
!echo "Вася, 2001 nПетя, 2000, nМикола,2003 n " > file.csv
!type file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv( "file.csv ")
df

"Вася, 2001 nПетя, 2000, nМикола,2003 n " 


Empty DataFrame
Columns: [Вася, 2001 nПетя, 2000, nМикола,2003 n  ]
Index: []

In [47]:
!echo "Вася , 2001" > file.csv
!echo "Петя , 2000" >> file.csv
!echo "Микола, 2003" >> file.csv
!type file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

"Вася , 2001" 
"Петя , 2000" 
"Микола, 2003" 


Ім'я  Рік народження
0   Вася , 2001              NaN
1   Петя , 2000              NaN
2  Микола, 2003              NaN

In [48]:
!(echo Вася, 2001 & echo Петя, 2000 & echo Микола, 2003) > file.csv
!type file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"])
df

Вася, 2001 
Петя, 2000 
Микола, 2003


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

### ЗАВДАННЯ

In [49]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
nums = np.random.randint(0, 50, 10, dtype="int16")
print(nums)
df1_1 = pd.DataFrame(nums)
df1_1

[28 47 18 35  5 32  5 33 47 32]


0
0  28
1  47
2  18
3  35
4   5
5  32
6   5
7  33
8  47
9  32

In [50]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 випадкових чисел з плаваючою точкою
komanum = np.random.random((5,6))
print(komanum)
df1_2 = pd.DataFrame(komanum)
df1_2

[[0.16781355 0.64698987 0.58507572 0.5811008  0.38460387 0.72678569]
 [0.4282377  0.21017384 0.82235076 0.28448838 0.8994474  0.95695155]
 [0.92226133 0.85215136 0.45074829 0.72397775 0.72414284 0.56308528]
 [0.81171791 0.71695589 0.4057212  0.89599485 0.03105192 0.32520009]
 [0.06323046 0.97676705 0.61873991 0.45950004 0.27620526 0.62979495]]


0         1         2         3         4         5
0  0.167814  0.646990  0.585076  0.581101  0.384604  0.726786
1  0.428238  0.210174  0.822351  0.284488  0.899447  0.956952
2  0.922261  0.852151  0.450748  0.723978  0.724143  0.563085
3  0.811718  0.716956  0.405721  0.895995  0.031052  0.325200
4  0.063230  0.976767  0.618740  0.459500  0.276205  0.629795

ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [51]:
dict_df = {
    "ім'я": ['Петро', 'Іван', 'Степан'],
    "прізвище": ['Петров', 'Іванов', 'Степанов'],
    "рік народження": [2000, 2002, 2001],
    "телефон": ['222-222-2222', '333-333-3333', '444-444-4444']
}
df1_3 = pd.DataFrame(dict_df)
df1_3

ім'я  прізвище  рік народження       телефон
0   Петро    Петров            2000  222-222-2222
1    Іван    Іванов            2002  333-333-3333
2  Степан  Степанов            2001  444-444-4444

In [52]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls
# !pip install openpyxl
df1_4 = pd.read_excel("sales.xlsx", nrows=20, index_col='rank')
df1_4

name platform  year  \
rank                                                                
1                                       Wii Sports      Wii  2006   
2                                Super Mario Bros.      NES  1985   
3                                   Mario Kart Wii      Wii  2008   
4                                Wii Sports Resort      Wii  2009   
5                         Pokemon Red/Pokemon Blue       GB  1996   
6                                           Tetris       GB  1989   
7                            New Super Mario Bros.       DS  2006   
8                                         Wii Play      Wii  2006   
9                        New Super Mario Bros. Wii      Wii  2009   
10                                       Duck Hunt      NES  1984   
11                                      Nintendogs       DS  2005   
12                                   Mario Kart DS       DS  2005   
13                     Pokemon Gold/Pokemon Silver       GB  1999   
14                                         Wii Fit      Wii  2007   
15                                    Wii Fit Plus      Wii  2009   
16                              Kinect Adventures!     X360  2010   
17                              Grand Theft Auto V      PS3  2013   
18                   Grand Theft Auto: San Andreas      PS2  2004   
19                               Super Mario World     SNES  1990   
20    Brain Age: Train Your Brain in Minutes a Day       DS  2005   

             genre               publisher  na_sales  eu_sales  jp_sales  \
rank                                                                       
1           Sports                Nintendo     41.49     29.02      3.77   
2         Platform                Nintendo     29.08      3.58      6.81   
3           Racing                Nintendo     15.85     12.88      3.79   
4           Sports                Nintendo     15.75     11.01      3.28   
5     Role-Playing                Nintendo     11.27      8.89     10.22   
6           Puzzle                Nintendo     23.20      2.26      4.22   
7         Platform                Nintendo     11.38      9.23      6.50   
8             Misc                Nintendo     14.03      9.20      2.93   
9         Platform                Nintendo     14.59      7.06      4.70   
10         Shooter                Nintendo     26.93      0.63      0.28   
11      Simulation                Nintendo      9.07     11.00      1.93   
12          Racing                Nintendo      9.81      7.57      4.13   
13    Role-Playing                Nintendo      9.00      6.18      7.20   
14          Sports                Nintendo      8.94      8.03      3.60   
15          Sports                Nintendo      9.09      8.59      2.53   
16            Misc  Microsoft Game Studios     14.97      4.94      0.24   
17          Action    Take-Two Interactive      7.01      9.27      0.97   
18          Action    Take-Two Interactive      9.43      0.40      0.41   
19        Platform                Nintendo     12.78      3.75      3.54   
20            Misc                Nintendo      4.75      9.26      4.16   

      other_sales  global_sales  
rank                             
1            8.46         82.74  
2            0.77         40.24  
3            3.31         35.82  
4            2.96         33.00  
5            1.00         31.37  
6            0.58         30.26  
7            2.90         30.01  
8            2.85         29.02  
9            2.26         28.62  
10           0.47         28.31  
11           2.75         24.76  
12           1.92         23.42  
13           0.71         23.10  
14           2.15         22.72  
15           1.79         22.00  
16           1.67         21.82  
17           4.14         21.40  
18          10.57         20.81  
19           0.55         20.61  
20           2.05         20.22

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [53]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [54]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [55]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [56]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [57]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [58]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [59]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [60]:
# перевірити тип колонки датасету
type(titanic['Age'])

pandas.core.series.Series

In [61]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male
6                            McCarthy, Mr. Timothy J  54.0    male
7                     Palsson, Master. Gosta Leonard   2.0    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [62]:
# вивести рядки з 100 по 110
titanic[100:110]

PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female   
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   
107          108         1       3            Moss, Mr. Albert Johan    male   
108          109         0       3                   Rekic, Mr. Tido    male   
109          110         1       3               Moran, Miss. Bertha  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
100  28.0      0      0   349245   7.8958   NaN        S  
101   NaN      0      0   349215   7.8958   NaN        S  
102  21.0      0      1    35281  77.2875   D26        S  
103  33.0      0      0     7540   8.6542   NaN        S  
104  37.0      2      0  3101276   7.9250   NaN        S  
105  28.0      0      0   349207   7.8958   NaN        S  
106  21.0      0      0   343120   7.6500   NaN        S  
107   NaN      0      0   312991   7.7750   NaN        S  
108  38.0      0      0   349249   7.8958   NaN        S  
109   NaN      1      0   371110  24.1500   NaN        Q

In [63]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [64]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

PassengerId  Survived  Pclass                          Name     Sex  Age  \
5             6         0       3              Moran, Mr. James    male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3       Masselmani, Mrs. Fatima  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C

In [65]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
13            14         0       3   
18            19         0       3   
..           ...       ...     ...   
872          873         0       1   
873          874         0       3   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
4        0    373450   8.0500          NaN        S  
13       5    347082  31.2750          NaN        S  
18       0    345763  18.0000          NaN        S  
..     ...       ...      ...          ...      ...  
872      0       695   5.0000  B51 B53 B55        S  
873      0    345765   9.0000          NaN        S  
881      0    349257   7.8958          NaN        S  
885      5    382652  29.1250          NaN        Q  
890      0    370376   7.7500          NaN        Q  

[266 rows x 12 columns]

### ЗАВДАННЯ

In [66]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [67]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
print(titanic['Age'].describe())
titanic['Fare'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64


count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [68]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
full_df = titanic[~titanic.isnull().any(axis=1)]
full_df.shape[0]

183

In [69]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
condition = (titanic.Survived == 1) & (titanic.Sex == 'female')
surv_fem = titanic[condition]
surv_fem.shape[0]

233

## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [71]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [72]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [73]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

int8


In [74]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

ім'я  вік  рейтинг   адреса
0  Петя   22       10     Київ
1  Вася  200        3  Бровари
2  Галя   21        2   Фастів

In [75]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася  200        6  Бровари
2  Галя   21        5   Фастів

In [76]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася   20        6  Бровари
2  Галя   21        5   Фастів

In [77]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

ім'я  рейтинг   адреса
0  Петя       13     Київ
1  Вася        6  Бровари
2  Галя        5   Фастів

In [78]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [79]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

PassengerId  Survived  Pclass  \
15            16         1       2   
730          731         1       1   
18            19         0       3   

                                                  Name     Sex   Age  SibSp  \
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
730                      Allen, Miss. Elisabeth Walton  female  29.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   

     Parch  Ticket      Fare Cabin Embarked  
15       0  248706   16.0000   NaN        S  
730      0   24160  211.3375    B5        S  
18       0  345763   18.0000   NaN        S

In [80]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
644          645         1       3                    Baclini, Miss. Eugenie   
469          470         1       3             Baclini, Miss. Helene Barbara   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
644  female  0.75      2      1        2666  19.2583   NaN        C  
469  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [81]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin     Embarked  
0        0         A/5 21171   7.2500   NaN  Southampton  
1        0          PC 17599  71.2833   C85    Cherbourg  
2        0  STON/O2. 3101282   7.9250   NaN  Southampton  
3        0            113803  53.1000  C123  Southampton  
4        0            373450   8.0500   NaN  Southampton  
..     ...               ...      ...   ...          ...  
886      0            211536  13.0000   NaN  Southampton  
887      0            112053  30.0000   B42  Southampton  
888      2        W./C. 6607  23.4500   NaN  Southampton  
889      0            111369  30.0000  C148    Cherbourg  
890      0            370376   7.7500   NaN   Queenstown  

[891 rows x 12 columns]

In [82]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

216

In [83]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin     Embarked  
0      0         A/5 21171   7.2500   ***  Southampton  
1      0          PC 17599  71.2833   C85    Cherbourg  
2      0  STON/O2. 3101282   7.9250   ***  Southampton

In [84]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

(712, 12)

### ЗАВДАННЯ

In [86]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [87]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
df['рік завершення школи'] = [2018, 2020, 200]
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                   200


In [88]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
df.loc[2, 'рік завершення школи'] = 2020
print(df)

   ім'я  вік рейтинг  рік завершення школи
0  Петя   22      10                  2018
1  Вася  200       3                  2020
2  Галя   21       2                  2020


In [89]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [98]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [102]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
filter = (titanic['Sex'] == 'male') & (titanic['Age'].between(20, 30) & (titanic['Pclass'] == 2))
titanic[filter].head()

PassengerId  Survived  Pclass                             Name   Sex  \
72            73         0       2             Hood, Mr. Ambrose Jr  male   
117          118         0       2  Turpin, Mr. William John Robert  male   
120          121         0       2      Hickman, Mr. Stanley George  male   
134          135         0       2   Sobey, Mr. Samuel James Hayden  male   
135          136         0       2               Richard, Mr. Emile  male   

      Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
72   21.0      0      0   S.O.C. 14879  73.5000   NaN        S  
117  29.0      1      0          11668  21.0000   NaN        S  
120  21.0      2      0   S.O.C. 14879  73.5000   NaN        S  
134  25.0      0      0     C.A. 29178  13.0000   NaN        S  
135  23.0      0      0  SC/PARIS 2133  15.0458   NaN        C

In [112]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = titanic.dropna(subset=["Fare"], how='all')
print('Number of null Fare values: ', titanic['Fare'].isnull().sum())
df

Number of null Fare values:  0


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [115]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
first_class = titanic[titanic['Pclass'] == 1]
avg_price = first_class['Fare'].mean()
print(avg_price)

84.1546875


## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [116]:
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [117]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64


In [119]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

Pclass  Sex   
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Sex, dtype: int64

In [120]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

Embarked           C          Q          S
Pclass                                    
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083

### ЗАВДАННЯ

In [121]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
group_sex = titanic.groupby(['Sex'])
max_age = group_sex['Age'].max()
print(max_age)

Sex
female    63.0
male      80.0
Name: Age, dtype: float64


___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [126]:
surv_table = titanic.pivot_table(values="Survived", index="Pclass", columns="Sex",
                   aggfunc=np.sum)
surv_table

Sex     female  male
Pclass              
1           91    45
2           70    17
3           72    47